const billAmount = document.getElementById('bill-amount')
const fivePercent = document.getElementById('five')
const numberOfPeople = document.getElementById('people-count')
const tipAmount = document.getElementById('tip-amount')
const totalAmount = document.getElementById('total-amount')